# Generated by Django 4.0.1 on 2022-01-12 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_celebrity_reporter_post_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
        migrations.AddField(
            model_name='post',
            name='reporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Blog.reporter'),
            preserve_default=False,
        ),
    ]
