# Generated by Django 4.0.1 on 2022-01-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_remove_post_autor_post_reporter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
