# Generated by Django 4.0.1 on 2022-01-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='resumo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
