# Generated by Django 4.0.1 on 2022-01-23 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_reporter_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.reporter'),
        ),
    ]
