# Generated by Django 4.0.1 on 2022-01-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_alter_post_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='foto_de_perfil',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
