# Generated by Django 4.0.1 on 2022-01-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_reporter_foto_de_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporter',
            name='foto',
        ),
    ]
