"""
Django settings for News_Blog project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path
from decouple import config,Csv#utilizar o Csv
from dj_database_url import parse as dburl
import django_on_heroku



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-()k1bm+y$uj=1lktzv4+u$p7qyp%&mbcg7v8$&(&*g7jt*^txc'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = config('DEBUG',default=False,cast=bool)
DEBUG = True

ALLOWED_HOSTS = config('ALLOWED_HOSTS',default=[],cast=Csv())#['*']#altear para acesso restrito ao heroku


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Blog',
    'ckeditor',
    'ckeditor_uploader',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'News_Blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],#'DIRS':[os.path.join(BASE_DIR,'templates')]
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'News_Blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
default_dburl = 'sqlite:///' + os.path.join(BASE_DIR,'db.sqlite3')#feito manualmente
DATABASES = {
    'default' : config('DATABASE_URL',default_dburl,cast=dburl)
    #'default': {
     #   'ENGINE': 'django.db.backends.sqlite3',
    #    'NAME': BASE_DIR / 'db.sqlite3',
    #}
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

urlhttp = 'http://localhost:8001/'
#STATIC_URL = 'static/'
#STATIC_URL = urlhttp + 'staticfiles/'
STATIC_URL = 'static/'
#STATIC_ROOT = os.path.join(BASE_DIR,'http://localhost:8001/staticfiles/')
STATIC_ROOT = '/staticfiles/'

#MEDIA_URL = 'http://localhost:8001/media/'
#MEDIA_ROOT = os.path.join(BASE_DIR,'http://localhost:8001/media/')
MEDIA_URL = 'media/'
MEDIA_ROOT = 'staticfiles/media/'

CKEDITOR_UPLOAD_PATH = 'uploads/'
#CKEDITOR_UPLOAD_PATH = 'http://localhost:8001/media/uploads/'

# Default primary key field type    
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'#arquivos cachaveis e suporte para comprensão de arquivos

django_on_heroku.settings(locals())